version: '3.3'
services:
  db:
    container_name: ai_resume_builder_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'ai_resume_builder'
      MYSQL_USER: 'ai_resume_builder'
      MYSQL_PASSWORD: 'ai_resume_builder'
      MYSQL_ROOT_PASSWORD: 'ai_resume_builder'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ai_resume_builder-db:/var/lib/mysql
volumes:
  ai_resume_builder-db: